##### Chapter 5 ##### 
### btree is the best
#deployment:
#  dockerhub:
#    branch: master
#    commands:
#      - $DOCKER_HUB_TRIGGER

#test:
#  override:   
#    - mocha 
version: 2
jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: <command>
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
